# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.right_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.right_btn.setGeometry(QtCore.QRect(230, 370, 75, 23))
        self.right_btn.setObjectName("right_btn")
        self.mirrror_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mirrror_btn.setGeometry(QtCore.QRect(300, 370, 75, 23))
        self.mirrror_btn.setObjectName("mirrror_btn")
        self.sharp_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sharp_btn.setGeometry(QtCore.QRect(370, 370, 75, 23))
        self.sharp_btn.setObjectName("sharp_btn")
        self.bw_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bw_btn.setGeometry(QtCore.QRect(440, 370, 75, 23))
        self.bw_btn.setObjectName("bw_btn")
        self.left_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.left_btn.setGeometry(QtCore.QRect(160, 370, 75, 23))
        self.left_btn.setObjectName("left_btn")
        self.dir_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dir_btn.setGeometry(QtCore.QRect(30, 60, 121, 23))
        self.dir_btn.setObjectName("dir_btn")
        self.files_list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.files_list.setGeometry(QtCore.QRect(30, 100, 121, 301))
        self.files_list.setObjectName("files_list")
        self.photo_lb = QtWidgets.QLabel(parent=self.centralwidget)
        self.photo_lb.setGeometry(QtCore.QRect(160, 230, 47, 13))
        self.photo_lb.setObjectName("photo_lb")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.right_btn.setText(_translate("MainWindow", "Вправо"))
        self.mirrror_btn.setText(_translate("MainWindow", "Дзеркало"))
        self.sharp_btn.setText(_translate("MainWindow", "Різкість"))
        self.bw_btn.setText(_translate("MainWindow", "ЧБ"))
        self.left_btn.setText(_translate("MainWindow", "Вліво"))
        self.dir_btn.setText(_translate("MainWindow", "Папка"))
        self.photo_lb.setText(_translate("MainWindow", "картинка"))
