# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 595)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.files_list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.files_list.setGeometry(QtCore.QRect(10, 40, 131, 501))
        self.files_list.setObjectName("files_list")
        self.dir_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dir_btn.setGeometry(QtCore.QRect(10, 10, 131, 23))
        self.dir_btn.setObjectName("dir_btn")
        self.left_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.left_btn.setGeometry(QtCore.QRect(360, 500, 171, 23))
        self.left_btn.setObjectName("left_btn")
        self.right_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.right_btn.setGeometry(QtCore.QRect(180, 500, 171, 23))
        self.right_btn.setObjectName("right_btn")
        self.mirror_brn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mirror_brn.setGeometry(QtCore.QRect(540, 500, 171, 23))
        self.mirror_brn.setObjectName("mirror_brn")
        self.sharp_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sharp_btn.setGeometry(QtCore.QRect(900, 500, 171, 23))
        self.sharp_btn.setObjectName("sharp_btn")
        self.bw_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bw_btn.setGeometry(QtCore.QRect(720, 500, 171, 23))
        self.bw_btn.setObjectName("bw_btn")
        self.photo_lb = QtWidgets.QLabel(parent=self.centralwidget)
        self.photo_lb.setGeometry(QtCore.QRect(170, 32, 821, 411))
        self.photo_lb.setObjectName("photo_lb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dir_btn.setText(_translate("MainWindow", "Папка"))
        self.left_btn.setText(_translate("MainWindow", "Вліво"))
        self.right_btn.setText(_translate("MainWindow", "Вправо"))
        self.mirror_brn.setText(_translate("MainWindow", "Дзеркало"))
        self.sharp_btn.setText(_translate("MainWindow", "Різкість"))
        self.bw_btn.setText(_translate("MainWindow", "Ч/Б"))
        self.photo_lb.setText(_translate("MainWindow", "картинка"))
